version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - observability
  api:
    image: ghcr.io/0gis0/tour-of-heroes-dotnet-api/tour-of-heroes-api:6b947c4
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Initial Catalog=heroes;Persist Security Info=False;User ID=sa;Password=P@ssword;TrustServerCertificate=True;
      - OTLP_ENDPOINT_URL=http://jaeger:4318
    ports:
      - "5010:5000"
    depends_on:
      - jaeger
    networks:
      - observability
  db:
    # image: mcr.microsoft.com/mssql/server:latest
    image:  mcr.microsoft.com/azure-sql-edge
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssword
      ACCEPT_EULA: Y
    networks:
      - observability
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
      LOG_LEVEL: "debug"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - observability
networks:
  observability:
